name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
      with:
          bundle: UnityHub.flatpak
          manifest-path: com.unity.UnityHub.yaml
          cache-key: flatpak-builder-${{ github.sha }}
